# Generated by Django 6.0.2 on 2026-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruthTableTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(help_text='Номер задания ЕГЭ (2, 5, 12, 24-27)')),
                ('title', models.CharField(max_length=255)),
                ('statement', models.TextField(help_text='Условие задачи')),
                ('difficulty', models.IntegerField(default=5, help_text='Сложность (1-10)')),
                ('concepts', models.JSONField(default=list, help_text='Связанные концепции')),
                ('expression', models.CharField(help_text='Логическое выражение, например: (A ∨ B) ∧ ¬C', max_length=255)),
                ('variables', models.JSONField(default=list, help_text="Список переменных: ['A', 'B', 'C']")),
                ('correct_answer', models.TextField(help_text='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Задание: Таблица истинности',
                'verbose_name_plural': 'Задания: Таблицы истинности',
            },
        ),
    ]
