# Generated by Django 6.0.2 on 2026-03-02 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('user_code', models.TextField(blank=True, help_text='Код пользователя')),
                ('user_answer', models.TextField(blank=True, help_text='Ответ пользователя')),
                ('is_correct', models.BooleanField(help_text='Правильность решения', null=True)),
                ('runtime', models.FloatField(help_text='Время выполнения (сек)', null=True)),
                ('memory', models.FloatField(help_text='Использованная память (MB)', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm_type', models.CharField(blank=True, help_text='Тип алгоритма: bruteforce, optimized, math, dp', max_length=50)),
                ('complexity_estimate', models.CharField(blank=True, help_text='Оценка сложности: O(n), O(n^2), etc.', max_length=20)),
                ('logic_errors', models.JSONField(default=list, help_text='Список логических ошибок')),
                ('feedback_text', models.TextField(blank=True, help_text='Текстовый фидбэк от AI')),
                ('suggested_approach', models.TextField(blank=True, help_text='Предложенный подход к решению')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Уверенность AI в анализе (0-1)')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='attempts.attempt')),
            ],
            options={
                'verbose_name': 'AI-анализ',
                'verbose_name_plural': 'AI-анализы',
            },
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='attempts_at_user_id_20fb61_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['-created_at'], name='attempts_at_created_780077_idx'),
        ),
    ]
