# Generated by Django 6.0.2 on 2026-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(help_text='Номер задания ЕГЭ (2, 5, 12, 24-27)')),
                ('title', models.CharField(max_length=255)),
                ('statement', models.TextField(help_text='Условие задачи')),
                ('difficulty', models.IntegerField(default=5, help_text='Сложность (1-10)')),
                ('concepts', models.JSONField(default=list, help_text='Связанные концепции')),
                ('input_description', models.TextField(help_text='Описание входных данных')),
                ('output_description', models.TextField(help_text='Описание выходных данных')),
                ('test_cases', models.JSONField(default=list, help_text="Тестовые случаи: [{'input': '...', 'output': '...'}]")),
                ('official_solution', models.TextField(blank=True, help_text='Официальное решение')),
                ('time_limit', models.FloatField(default=5.0, help_text='Лимит времени (сек)')),
                ('memory_limit', models.IntegerField(default=256, help_text='Лимит памяти (MB)')),
            ],
            options={
                'verbose_name': 'Задание: Python-код',
                'verbose_name_plural': 'Задания: Python-код',
            },
        ),
    ]
